name: build

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # 5.2.0
        with:
          dotnet-version: '8.0.x'

      - name: Publish exe
        run: >
          dotnet publish MonitoringApp.Tray/MonitoringApp.Tray.csproj
          -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true

      - name: Build installer (Inno Setup)
        shell: cmd
        run: '"%ProgramFiles(x86)%\Inno Setup 6\ISCC.exe" Installer\setup.iss'

      - name: Upload exe
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
        with:
          name: MechrevoMonitorTray-exe
          path: MonitoringApp.Tray/bin/Release/net8.0-windows/win-x64/publish/MechrevoMonitorTray.exe

      - name: Upload installer
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
        with:
          name: MechrevoMonitorTray-Setup
          path: Installer/Output/MechrevoMonitorTray-Setup-*.exe
